// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *Limit) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Cost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integer value, decimal(8, 2) in MySQL
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// currency code, for example RUB
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *Cost) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Cost) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Default       bool                   `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *Car) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Car) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Car) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Car) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Car) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CarCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarCollection) Reset() {
	*x = CarCollection{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarCollection) ProtoMessage() {}

func (x *CarCollection) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarCollection.ProtoReflect.Descriptor instead.
func (*CarCollection) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *CarCollection) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *CarCollection) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type FillingStation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillingStation) Reset() {
	*x = FillingStation{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillingStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillingStation) ProtoMessage() {}

func (x *FillingStation) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillingStation.ProtoReflect.Descriptor instead.
func (*FillingStation) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *FillingStation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FillingStation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FillingStation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FillingStationCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*FillingStation      `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillingStationCollection) Reset() {
	*x = FillingStationCollection{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillingStationCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillingStationCollection) ProtoMessage() {}

func (x *FillingStationCollection) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillingStationCollection.ProtoReflect.Descriptor instead.
func (*FillingStationCollection) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *FillingStationCollection) GetStations() []*FillingStation {
	if x != nil {
		return x.Stations
	}
	return nil
}

type FuelType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelType) Reset() {
	*x = FuelType{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelType) ProtoMessage() {}

func (x *FuelType) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelType.ProtoReflect.Descriptor instead.
func (*FuelType) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *FuelType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FuelType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FuelTypeCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*FuelType            `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelTypeCollection) Reset() {
	*x = FuelTypeCollection{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelTypeCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelTypeCollection) ProtoMessage() {}

func (x *FuelTypeCollection) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelTypeCollection.ProtoReflect.Descriptor instead.
func (*FuelTypeCollection) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *FuelTypeCollection) GetTypes() []*FuelType {
	if x != nil {
		return x.Types
	}
	return nil
}

type Fuel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cost  *Cost                  `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	// integer value, decimal(8, 2) in MySQL
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Station       *FillingStation        `protobuf:"bytes,4,opt,name=station,proto3" json:"station,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Distance      int32                  `protobuf:"varint,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Car           *Car                   `protobuf:"bytes,7,opt,name=car,proto3" json:"car,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type          *FuelType              `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fuel) Reset() {
	*x = Fuel{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fuel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fuel) ProtoMessage() {}

func (x *Fuel) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fuel.ProtoReflect.Descriptor instead.
func (*Fuel) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *Fuel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Fuel) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Fuel) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Fuel) GetStation() *FillingStation {
	if x != nil {
		return x.Station
	}
	return nil
}

func (x *Fuel) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Fuel) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Fuel) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

func (x *Fuel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Fuel) GetType() *FuelType {
	if x != nil {
		return x.Type
	}
	return nil
}

type FuelCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fuels         []*Fuel                `protobuf:"bytes,1,rep,name=fuels,proto3" json:"fuels,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelCollection) Reset() {
	*x = FuelCollection{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelCollection) ProtoMessage() {}

func (x *FuelCollection) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelCollection.ProtoReflect.Descriptor instead.
func (*FuelCollection) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *FuelCollection) GetFuels() []*Fuel {
	if x != nil {
		return x.Fuels
	}
	return nil
}

func (x *FuelCollection) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Currency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// currency code, for example RUB
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Default       bool                   `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *Currency) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Currency) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DefaultCurrency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultCurrency) Reset() {
	*x = DefaultCurrency{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultCurrency) ProtoMessage() {}

func (x *DefaultCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultCurrency.ProtoReflect.Descriptor instead.
func (*DefaultCurrency) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *DefaultCurrency) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *DefaultCurrency) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type CurrencyCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyCollection) Reset() {
	*x = CurrencyCollection{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyCollection) ProtoMessage() {}

func (x *CurrencyCollection) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyCollection.ProtoReflect.Descriptor instead.
func (*CurrencyCollection) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *CurrencyCollection) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type PaginationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       int32                  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Last          int32                  `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMeta) Reset() {
	*x = PaginationMeta{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMeta) ProtoMessage() {}

func (x *PaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMeta.ProtoReflect.Descriptor instead.
func (*PaginationMeta) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *PaginationMeta) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PaginationMeta) GetLast() int32 {
	if x != nil {
		return x.Last
	}
	return 0
}

type UserSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DefaultCar      *Car                   `protobuf:"bytes,2,opt,name=default_car,json=defaultCar,proto3" json:"default_car,omitempty"`
	DefaultCurrency *Currency              `protobuf:"bytes,3,opt,name=default_currency,json=defaultCurrency,proto3" json:"default_currency,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *UserSettings) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSettings) GetDefaultCar() *Car {
	if x != nil {
		return x.DefaultCar
	}
	return nil
}

func (x *UserSettings) GetDefaultCurrency() *Currency {
	if x != nil {
		return x.DefaultCurrency
	}
	return nil
}

func (x *UserSettings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x1bxelbot.com.autonotes.server\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n" +
	"\x05Limit\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"8\n" +
	"\x04Cost\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xa4\x01\n" +
	"\x03Car\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03vin\x18\x03 \x01(\tR\x03vin\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x18\n" +
	"\adefault\x18\x05 \x01(\bR\adefault\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x86\x01\n" +
	"\rCarCollection\x124\n" +
	"\x04cars\x18\x01 \x03(\v2 .xelbot.com.autonotes.server.CarR\x04cars\x12?\n" +
	"\x04meta\x18\x02 \x01(\v2+.xelbot.com.autonotes.server.PaginationMetaR\x04meta\"o\n" +
	"\x0eFillingStation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x18FillingStationCollection\x12G\n" +
	"\bstations\x18\x01 \x03(\v2+.xelbot.com.autonotes.server.FillingStationR\bstations\".\n" +
	"\bFuelType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Q\n" +
	"\x12FuelTypeCollection\x12;\n" +
	"\x05types\x18\x01 \x03(\v2%.xelbot.com.autonotes.server.FuelTypeR\x05types\"\xa0\x03\n" +
	"\x04Fuel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x125\n" +
	"\x04cost\x18\x02 \x01(\v2!.xelbot.com.autonotes.server.CostR\x04cost\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12E\n" +
	"\astation\x18\x04 \x01(\v2+.xelbot.com.autonotes.server.FillingStationR\astation\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x05R\bdistance\x122\n" +
	"\x03car\x18\a \x01(\v2 .xelbot.com.autonotes.server.CarR\x03car\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\x04type\x18\t \x01(\v2%.xelbot.com.autonotes.server.FuelTypeR\x04type\"\x8a\x01\n" +
	"\x0eFuelCollection\x127\n" +
	"\x05fuels\x18\x01 \x03(\v2!.xelbot.com.autonotes.server.FuelR\x05fuels\x12?\n" +
	"\x04meta\x18\x02 \x01(\v2+.xelbot.com.autonotes.server.PaginationMetaR\x04meta\"\x97\x01\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\adefault\x18\x04 \x01(\bR\adefault\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x0fDefaultCurrency\x12A\n" +
	"\bcurrency\x18\x01 \x01(\v2%.xelbot.com.autonotes.server.CurrencyR\bcurrency\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"[\n" +
	"\x12CurrencyCollection\x12E\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2%.xelbot.com.autonotes.server.CurrencyR\n" +
	"currencies\">\n" +
	"\x0ePaginationMeta\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x05R\acurrent\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x05R\x04last\"\xa9\x02\n" +
	"\fUserSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12A\n" +
	"\vdefault_car\x18\x02 \x01(\v2 .xelbot.com.autonotes.server.CarR\n" +
	"defaultCar\x12P\n" +
	"\x10default_currency\x18\x03 \x01(\v2%.xelbot.com.autonotes.server.CurrencyR\x0fdefaultCurrency\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xd5\x03\n" +
	"\x0eUserRepository\x12M\n" +
	"\aGetCars\x12\x16.google.protobuf.Empty\x1a*.xelbot.com.autonotes.server.CarCollection\x12X\n" +
	"\rGetCurrencies\x12\x16.google.protobuf.Empty\x1a/.xelbot.com.autonotes.server.CurrencyCollection\x12Z\n" +
	"\x12GetDefaultCurrency\x12\x16.google.protobuf.Empty\x1a,.xelbot.com.autonotes.server.DefaultCurrency\x12T\n" +
	"\x0fGetUserSettings\x12\x16.google.protobuf.Empty\x1a).xelbot.com.autonotes.server.UserSettings\x12h\n" +
	"\x10SaveUserSettings\x12).xelbot.com.autonotes.server.UserSettings\x1a).xelbot.com.autonotes.server.UserSettings2\xfd\x02\n" +
	"\x0eFuelRepository\x12[\n" +
	"\bGetFuels\x12\".xelbot.com.autonotes.server.Limit\x1a+.xelbot.com.autonotes.server.FuelCollection\x12c\n" +
	"\x12GetFillingStations\x12\x16.google.protobuf.Empty\x1a5.xelbot.com.autonotes.server.FillingStationCollection\x12W\n" +
	"\fGetFuelTypes\x12\x16.google.protobuf.Empty\x1a/.xelbot.com.autonotes.server.FuelTypeCollection\x12P\n" +
	"\bSaveFuel\x12!.xelbot.com.autonotes.server.Fuel\x1a!.xelbot.com.autonotes.server.FuelBTZ'xelbot.com/auto-notes/server/rpc/server\xca\x02\x10AutoNotes\\Server\xe2\x02\x15AutoNotes\\Server\\Metab\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_proto_goTypes = []any{
	(*Limit)(nil),                    // 0: xelbot.com.autonotes.server.Limit
	(*Cost)(nil),                     // 1: xelbot.com.autonotes.server.Cost
	(*Car)(nil),                      // 2: xelbot.com.autonotes.server.Car
	(*CarCollection)(nil),            // 3: xelbot.com.autonotes.server.CarCollection
	(*FillingStation)(nil),           // 4: xelbot.com.autonotes.server.FillingStation
	(*FillingStationCollection)(nil), // 5: xelbot.com.autonotes.server.FillingStationCollection
	(*FuelType)(nil),                 // 6: xelbot.com.autonotes.server.FuelType
	(*FuelTypeCollection)(nil),       // 7: xelbot.com.autonotes.server.FuelTypeCollection
	(*Fuel)(nil),                     // 8: xelbot.com.autonotes.server.Fuel
	(*FuelCollection)(nil),           // 9: xelbot.com.autonotes.server.FuelCollection
	(*Currency)(nil),                 // 10: xelbot.com.autonotes.server.Currency
	(*DefaultCurrency)(nil),          // 11: xelbot.com.autonotes.server.DefaultCurrency
	(*CurrencyCollection)(nil),       // 12: xelbot.com.autonotes.server.CurrencyCollection
	(*PaginationMeta)(nil),           // 13: xelbot.com.autonotes.server.PaginationMeta
	(*UserSettings)(nil),             // 14: xelbot.com.autonotes.server.UserSettings
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 16: google.protobuf.Empty
}
var file_server_proto_depIdxs = []int32{
	15, // 0: xelbot.com.autonotes.server.Car.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: xelbot.com.autonotes.server.CarCollection.cars:type_name -> xelbot.com.autonotes.server.Car
	13, // 2: xelbot.com.autonotes.server.CarCollection.meta:type_name -> xelbot.com.autonotes.server.PaginationMeta
	15, // 3: xelbot.com.autonotes.server.FillingStation.created_at:type_name -> google.protobuf.Timestamp
	4,  // 4: xelbot.com.autonotes.server.FillingStationCollection.stations:type_name -> xelbot.com.autonotes.server.FillingStation
	6,  // 5: xelbot.com.autonotes.server.FuelTypeCollection.types:type_name -> xelbot.com.autonotes.server.FuelType
	1,  // 6: xelbot.com.autonotes.server.Fuel.cost:type_name -> xelbot.com.autonotes.server.Cost
	4,  // 7: xelbot.com.autonotes.server.Fuel.station:type_name -> xelbot.com.autonotes.server.FillingStation
	15, // 8: xelbot.com.autonotes.server.Fuel.date:type_name -> google.protobuf.Timestamp
	2,  // 9: xelbot.com.autonotes.server.Fuel.car:type_name -> xelbot.com.autonotes.server.Car
	15, // 10: xelbot.com.autonotes.server.Fuel.created_at:type_name -> google.protobuf.Timestamp
	6,  // 11: xelbot.com.autonotes.server.Fuel.type:type_name -> xelbot.com.autonotes.server.FuelType
	8,  // 12: xelbot.com.autonotes.server.FuelCollection.fuels:type_name -> xelbot.com.autonotes.server.Fuel
	13, // 13: xelbot.com.autonotes.server.FuelCollection.meta:type_name -> xelbot.com.autonotes.server.PaginationMeta
	15, // 14: xelbot.com.autonotes.server.Currency.created_at:type_name -> google.protobuf.Timestamp
	10, // 15: xelbot.com.autonotes.server.DefaultCurrency.currency:type_name -> xelbot.com.autonotes.server.Currency
	10, // 16: xelbot.com.autonotes.server.CurrencyCollection.currencies:type_name -> xelbot.com.autonotes.server.Currency
	2,  // 17: xelbot.com.autonotes.server.UserSettings.default_car:type_name -> xelbot.com.autonotes.server.Car
	10, // 18: xelbot.com.autonotes.server.UserSettings.default_currency:type_name -> xelbot.com.autonotes.server.Currency
	15, // 19: xelbot.com.autonotes.server.UserSettings.created_at:type_name -> google.protobuf.Timestamp
	15, // 20: xelbot.com.autonotes.server.UserSettings.updated_at:type_name -> google.protobuf.Timestamp
	16, // 21: xelbot.com.autonotes.server.UserRepository.GetCars:input_type -> google.protobuf.Empty
	16, // 22: xelbot.com.autonotes.server.UserRepository.GetCurrencies:input_type -> google.protobuf.Empty
	16, // 23: xelbot.com.autonotes.server.UserRepository.GetDefaultCurrency:input_type -> google.protobuf.Empty
	16, // 24: xelbot.com.autonotes.server.UserRepository.GetUserSettings:input_type -> google.protobuf.Empty
	14, // 25: xelbot.com.autonotes.server.UserRepository.SaveUserSettings:input_type -> xelbot.com.autonotes.server.UserSettings
	0,  // 26: xelbot.com.autonotes.server.FuelRepository.GetFuels:input_type -> xelbot.com.autonotes.server.Limit
	16, // 27: xelbot.com.autonotes.server.FuelRepository.GetFillingStations:input_type -> google.protobuf.Empty
	16, // 28: xelbot.com.autonotes.server.FuelRepository.GetFuelTypes:input_type -> google.protobuf.Empty
	8,  // 29: xelbot.com.autonotes.server.FuelRepository.SaveFuel:input_type -> xelbot.com.autonotes.server.Fuel
	3,  // 30: xelbot.com.autonotes.server.UserRepository.GetCars:output_type -> xelbot.com.autonotes.server.CarCollection
	12, // 31: xelbot.com.autonotes.server.UserRepository.GetCurrencies:output_type -> xelbot.com.autonotes.server.CurrencyCollection
	11, // 32: xelbot.com.autonotes.server.UserRepository.GetDefaultCurrency:output_type -> xelbot.com.autonotes.server.DefaultCurrency
	14, // 33: xelbot.com.autonotes.server.UserRepository.GetUserSettings:output_type -> xelbot.com.autonotes.server.UserSettings
	14, // 34: xelbot.com.autonotes.server.UserRepository.SaveUserSettings:output_type -> xelbot.com.autonotes.server.UserSettings
	9,  // 35: xelbot.com.autonotes.server.FuelRepository.GetFuels:output_type -> xelbot.com.autonotes.server.FuelCollection
	5,  // 36: xelbot.com.autonotes.server.FuelRepository.GetFillingStations:output_type -> xelbot.com.autonotes.server.FillingStationCollection
	7,  // 37: xelbot.com.autonotes.server.FuelRepository.GetFuelTypes:output_type -> xelbot.com.autonotes.server.FuelTypeCollection
	8,  // 38: xelbot.com.autonotes.server.FuelRepository.SaveFuel:output_type -> xelbot.com.autonotes.server.Fuel
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
