version: '2'
services:
    source:
        image: alpine:3.6
        volumes:
            - .:/var/www/html

    app:
        build:
            context: ./docker/web
            args:
                HOST_UID: ${HOST_UID}
        hostname: "autonotes"
        container_name: "autonotes"
        volumes_from:
            - source
        depends_on:
            - source
            - database

    database:
        build:
            context: ./docker/db
            args:
                HOST_UID: ${HOST_UID}
        ports:
            - "5432:5432"
        volumes:
            - ./var/db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: autonotes
            POSTGRES_DB: autonotes
            PGDATA: /var/lib/postgresql/data/pgdata

    nginx:
        build: ./docker/nginx
        volumes_from:
            - source
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - app
