POST http://localhost:8080/twirp/xelbot.com.autonotes.Auth/GetToken
Accept: application/json
Content-Type: application/json

{
  "username": "morontt",
  "password": "test"
}

###
POST http://localhost:8080/twirp/xelbot.com.autonotes.Auth/RefreshToken
Accept: application/json
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVuYW1lIjoibW9yb250dCIsImlhdCI6MTcxNzQyNTM5MiwiZXhwIjoxNzIwMDE3MzkyfQ.afrOxazij4tpWaud4uNZNkSQAKWjQlTkuNEpa8Aog4I"
}
