POST http://localhost:8080/twirp/xelbot.com.autonotes.Auth/GetToken
Accept: application/json
Content-Type: application/json

{
  "username": "morontt",
  "password": "test"
}

###
POST http://localhost:8080/twirp/xelbot.com.autonotes.Auth/RefreshToken
Accept: application/json
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVuYW1lIjoibW9yb250dCIsImlhdCI6MTcxNzM1OTcxNywiZXhwIjoxNzE5OTUxNzE3fQ.4fw_kxvCMyxVaK7Y5-XEIlrVvvWQLcpt1uVe35jLRDM"
}
