POST http://localhost:8080/twirp/xelbot.com.autonotes.server.UserRepository/GetCars
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{}

###
POST http://localhost:8080/twirp/xelbot.com.autonotes.server.UserRepository/GetCurrencies
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{}

###
POST http://localhost:8080/twirp/xelbot.com.autonotes.server.UserRepository/GetDefaultCurrency
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{}

###
POST http://localhost:8080/twirp/xelbot.com.autonotes.server.UserRepository/GetUserSettings
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{}
